# Generated by Django 4.2.11 on 2024-04-07 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID пользователя в telegram')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя в telegram')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия в telegram')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Никнейм в telegram')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, unique=True, verbose_name='Текст вопроса')),
                ('answer_text', models.TextField(verbose_name='Ответ вопроса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_questions', to='telegram.tguser', verbose_name='Пользователь')),
            ],
        ),
    ]
